### ISSUE TITLE
Are "short" names okay for display?

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#98]
In a [comment](https://github.com/Code4Nepal/nepalmap_federal/pull/95#issuecomment-568274043) on #95, I suggested using shorter names for the "name" field in the geography table and using full names for the "long name" field. (An example would be "Parivartan" versus "Parivartan Rural Municipality".) I incorrectly stated that the "long name" field would be displayed in the main box that shows for a locality. Instead the short "name" shows up. The "long name" is still what is shown as an option when searching, but the shorter "name" is what is displayed. 

Is that okay and appropriate?

Here is an example of the main profile view showing a shorter "name" being used: 

https://beta.nepalmap.org/profiles/local-53001-parivartan/

Here is a data table view showing that the full name is used in this view:
https://beta.nepalmap.org/data/table/?table=LIGHTINGFUEL&geo_ids=local|district-58&primary_geo_id=local-53001

**Comment by ravinepal** [comment]
should be fine. let's see what @nikeshbalami advises.

**Comment by nikeshbalami** [comment]
Since the "**long_name**" is shown as an option while searching, I believe having "**name**" at display and map will be okay/works fine, because the chances of using the search function by most of the users are high.

More, importantly having a "long_name" at the map makes it looks messy during the time of hover, so I am quite satisfied with the current update.

**Putting this on the record**
"long_name" for Search
"name" for Display and Map
